name: CI/CD Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    lint-and-format:
        name: Lint e Formatação
        runs-on: ubuntu-latest

        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Instalar dependências
              run: npm ci

            - name: Executar ESLint
              run: npm run lint

            - name: Verificar formatação Prettier
              run: npm run format:check

    build:
        name: Build TypeScript
        runs-on: ubuntu-latest
        needs: lint-and-format

        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Instalar dependências
              run: npm ci

            - name: Build TypeScript
              run: npm run build

            - name: Upload artifacts de build
              uses: actions/upload-artifact@v3
              with:
                  name: build-files
                  path: dist/

    test:
        name: Testes Unitários
        runs-on: ubuntu-latest
        needs: lint-and-format

        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Instalar dependências
              run: npm ci

            - name: Executar testes
              run: npm run test:coverage

            - name: Upload coverage para Codecov
              uses: codecov/codecov-action@v3
              with:
                  file: ./coverage/lcov.info
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: false

    security:
        name: Auditoria de Segurança
        runs-on: ubuntu-latest

        steps:
            - name: Checkout código
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Instalar dependências
              run: npm ci

            - name: Auditoria de segurança
              run: npm audit --audit-level=moderate
